### ISSUE TITLE
Allow configuration of port

### ISSUE THREAD

**Issue by MartinHlavna** [donny-dont/speakeasy#3]
Hello,
i can see in speakeasy.dart, that port is hardcoded for 8080.  Is there any possibility for configuring this port?

**Comment by donny-dont** [comment]
@MartinHlavna nothing currently. There is a docker container available which by its nature would let you expose it to whatever you want.

Also I moved everything to https://github.com/speakeasy-pub/speakeasy. If you want to open an issue there feel free.
